
/*
 * 
 */

package co.com.suramericana.seus.ws.servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import co.com.suramericana.seus.ws.interfaces.SeusWs;
import javax.xml.ws.Service;

import com.pratech.accesscontroldb.common.Configuration;
import com.pratech.accesscontroldb.persistence.Store;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Aug 25 16:49:10 COT 2011
 * Generated source version: 2.1.4
 * 
 */


@WebServiceClient(name = "SeusWsImplService", 
                  wsdlLocation = "http://apps02.suranet.com/seus-soa/services/SeusWs?wsdl",
                  targetNamespace = "http://servicios.ws.seus.suramericana.com.co/") 
public class SeusWsImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://servicios.ws.seus.suramericana.com.co/", "SeusWsImplService");
    public final static QName SeusWsImplPort = new QName("http://servicios.ws.seus.suramericana.com.co/", "SeusWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL(Configuration.getInstance().getProperty("wsdlLocation"));
        } catch (MalformedURLException e) {
			//Registrar excepción
			e.printStackTrace();
			Store.getInstance().error("NA", "Can not initialize the default wsdl from http://apps02.suranet.com/seus-soa/services/SeusWs?wsdl", e);
        }
        WSDL_LOCATION = url;
    }

    public SeusWsImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SeusWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeusWsImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SeusWs
     */
    @WebEndpoint(name = "SeusWsImplPort")
    public SeusWs getSeusWsImplPort() {
        return super.getPort(SeusWsImplPort, SeusWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SeusWs
     */
    @WebEndpoint(name = "SeusWsImplPort")
    public SeusWs getSeusWsImplPort(WebServiceFeature... features) {
        return super.getPort(SeusWsImplPort, SeusWs.class, features);
    }

}
