package co.com.suramericana.seus.ws.interfaces;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.soap.SOAPFaultException;

import co.com.suramericana.seus.ws.servicios.SeusWsImplService;

import com.pratech.accesscontroldb.client.ACDBException;
import com.pratech.accesscontroldb.persistence.Store;

/**
 * This class was generated by Apache CXF 2.1.4 Mon Aug 22 11:01:21 COT 2011
 * Generated source version: 2.1.4
 * 
 */

public class SeusWs_SeusWsImplPort_Client {

	private QName _SERVICE_NAME;

	public SeusWs_SeusWsImplPort_Client(String serviceName, String servicio) {

		// SERVICE_NAME = new
		// QName("http://servicios.ws.seus.suramericana.com.co/",
		// "SeusWsImplService");
		_SERVICE_NAME = new QName(serviceName, servicio);
	}

	public co.com.suramericana.seus.ws.bo.UsuarioSeus getUser(String token) throws ACDBException {
		URL wsdlURL = SeusWsImplService.WSDL_LOCATION;

		SeusWsImplService ss = new SeusWsImplService(wsdlURL, _SERVICE_NAME);
		SeusWs port = ss.getSeusWsImplPort();
		co.com.suramericana.seus.ws.bo.UsuarioSeus _getInfoUsuarioFromTokenSeus__return = null;

		try {
			_getInfoUsuarioFromTokenSeus__return = port
				.getInfoUsuarioFromTokenSeus(token);
		} catch (SOAPFaultException e) {
			//Registrar excepción
			e.printStackTrace();
			Store.getInstance().error("NA", "Error SOAP al obtener información de token", e);
			
			throw new ACDBException("Es probable que su sesi\u00f3n haya expirado. Por favor ingrese de nuevo.");
		}

		return _getInfoUsuarioFromTokenSeus__return;

	}

}
