
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package co.com.suramericana.seus.ws.interfaces;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.pratech.accesscontroldb.persistence.Store;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Aug 22 11:01:21 COT 2011
 * Generated source version: 2.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "SeusWsImplService",
                      portName = "SeusWsImplPort",
                      targetNamespace = "http://servicios.ws.seus.suramericana.com.co/",
                      wsdlLocation = "http://mdeaps03.suranet.com:7778/seus-soa/services/SeusWs?wsdl",
                      endpointInterface = "co.com.suramericana.seus.ws.interfaces.SeusWs")
                      
public class SeusWsImpl implements SeusWs {

    private static final Logger LOG = Logger.getLogger(SeusWsImpl.class.getName());

    /* (non-Javadoc)
     * @see co.com.suramericana.seus.ws.interfaces.SeusWs#autenticar(java.lang.String  login ,)java.lang.String  password ,)java.lang.String  ip )*
     */
    public co.com.suramericana.seus.ws.bo.AutenticacionSeus autenticar(java.lang.String login,java.lang.String password,java.lang.String ip) { 
        LOG.info("Executing operation autenticar");
        System.out.println(login);
        System.out.println(password);
        System.out.println(ip);
        try {
            co.com.suramericana.seus.ws.bo.AutenticacionSeus _return = null;
            return _return;
        } catch (Exception e) {
			//Registrar excepción
			e.printStackTrace();
			Store.getInstance().error("NA", "Error al autenticar", e);

            throw new RuntimeException(e);
        }
    }

    /* (non-Javadoc)
     * @see co.com.suramericana.seus.ws.interfaces.SeusWs#getAplicacionesUsuario(java.lang.String  token )*
     */
    public co.com.suramericana.seus.ws.bo.ArrayOfAplicacionSeus getAplicacionesUsuario(java.lang.String token) { 
        LOG.info("Executing operation getAplicacionesUsuario");
        System.out.println(token);
        try {
            co.com.suramericana.seus.ws.bo.ArrayOfAplicacionSeus _return = null;
            return _return;
        } catch (Exception e) {
			//Registrar excepción
			e.printStackTrace();
			Store.getInstance().error("NA", "Error al obtener aplicaciones de usuario", e);
			
            throw new RuntimeException(e);
        }
    }

    /* (non-Javadoc)
     * @see co.com.suramericana.seus.ws.interfaces.SeusWs#getInfoUsuarioFromTokenSeus(java.lang.String  token )*
     */
    public co.com.suramericana.seus.ws.bo.UsuarioSeus getInfoUsuarioFromTokenSeus(java.lang.String token) { 
        LOG.info("Executing operation getInfoUsuarioFromTokenSeus");
        System.out.println(token);
        try {
            co.com.suramericana.seus.ws.bo.UsuarioSeus _return = null;
            return _return;
        } catch (Exception e) {
			//Registrar excepción
			e.printStackTrace();
			Store.getInstance().error("NA", "Error al obtener usuario de token Seus", e);
			
            throw new RuntimeException(e);
        }
    }

}
