package co.com.suramericana.seus.ws.interfaces;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import co.com.suramericana.seus.ws.servicios.SeusWsImplService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.4 Mon Aug 22 11:01:21 COT 2011
 * Generated source version: 2.1.4
 * 
 */

public class SeusWs_SeusWsImplPort_Client {

	private QName _SERVICE_NAME;

	public SeusWs_SeusWsImplPort_Client(String serviceName, String servicio) {

		// SERVICE_NAME = new
		// QName("http://servicios.ws.seus.suramericana.com.co/",
		// "SeusWsImplService");
		_SERVICE_NAME = new QName(serviceName, servicio);
	}

	public co.com.suramericana.seus.ws.bo.UsuarioSeus getUser(String token) {
		URL wsdlURL = SeusWsImplService.WSDL_LOCATION;

		SeusWsImplService ss = new SeusWsImplService(wsdlURL, _SERVICE_NAME);
		SeusWs port = ss.getSeusWsImplPort();

		co.com.suramericana.seus.ws.bo.UsuarioSeus _getInfoUsuarioFromTokenSeus__return = port
				.getInfoUsuarioFromTokenSeus(token);

		return _getInfoUsuarioFromTokenSeus__return;

	}

}
