package co.com.suramericana.seus.ws.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Aug 25 16:49:10 COT 2011
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://interfaces.ws.seus.suramericana.com.co/", name = "SeusWs")
@XmlSeeAlso({co.com.suramericana.seus.ws.bo.ObjectFactory.class,ObjectFactory.class,co.com.suramericana.seus.ws.servicios.ObjectFactory.class})
public interface SeusWs {

    @ResponseWrapper(localName = "AutenticarResponse", targetNamespace = "http://interfaces.ws.seus.suramericana.com.co/", className = "co.com.suramericana.seus.ws.interfaces.AutenticarResponse")
    @RequestWrapper(localName = "Autenticar", targetNamespace = "http://interfaces.ws.seus.suramericana.com.co/", className = "co.com.suramericana.seus.ws.interfaces.Autenticar")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod(operationName = "Autenticar")
    public co.com.suramericana.seus.ws.bo.AutenticacionSeus autenticar(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "ip", targetNamespace = "")
        java.lang.String ip
    );

    @ResponseWrapper(localName = "getAplicacionesUsuarioResponse", targetNamespace = "http://interfaces.ws.seus.suramericana.com.co/", className = "co.com.suramericana.seus.ws.interfaces.GetAplicacionesUsuarioResponse")
    @RequestWrapper(localName = "getAplicacionesUsuario", targetNamespace = "http://interfaces.ws.seus.suramericana.com.co/", className = "co.com.suramericana.seus.ws.interfaces.GetAplicacionesUsuario")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public co.com.suramericana.seus.ws.bo.ArrayOfAplicacionSeus getAplicacionesUsuario(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    );

    @ResponseWrapper(localName = "getInfoUsuarioFromTokenSeusResponse", targetNamespace = "http://interfaces.ws.seus.suramericana.com.co/", className = "co.com.suramericana.seus.ws.interfaces.GetInfoUsuarioFromTokenSeusResponse")
    @RequestWrapper(localName = "getInfoUsuarioFromTokenSeus", targetNamespace = "http://interfaces.ws.seus.suramericana.com.co/", className = "co.com.suramericana.seus.ws.interfaces.GetInfoUsuarioFromTokenSeus")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public co.com.suramericana.seus.ws.bo.UsuarioSeus getInfoUsuarioFromTokenSeus(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    );
}
